language: ruby
rvm: 2.2.4
script: bundle exec rspec
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    - secure: qTDzlxWUYQMBUM5RhDyfZQWkeI/e2q9X6mGm9/RiwFpWqw/0OXGqnb1cSAABJZFCMh8az8Cu1O6WlpALCUrE9Pr3NZcn/EpIxQF2lIeXboIiIhhGDp7s3qEE3iyLXSEKgviXuZXRBKseVyVklaTV2Em2V6GYQjhiDjuynXlKYbtQXpWI4Zh8AddWHeCPIM+GeNspXf/1j6JRzkHI5qVfU01PxGSfCdCN5SuFpzv14N96PCQmFRS14RrkI7FCClEah2QtOvSggTUcDccABZy+yacHg5ZuHTjYvcY18pbiGdIpQQCocZs1QWYW3V7sM3+sBWzLayADkOzmtIa1uK3NVRHtqEb3jQp7U3lZgoccu84I+a7Doc4TXu1/wjHuPgYJkMg9RxNeQOSi7KrS+H6283o6Z3WkQ2sGfMherusqoNrU8UA0DrldRobBu6gKMeSw9+jllv25R/dj4wJNbYN9avARtgvJUjBwanTDORRIIdeWdrhGWm3jIbxiqrhM67CaU6pkesxzZiwsVVGhJKQ6hx9fnUTHTDYrt3li6BKivxnYf8n3Xg/xS7u3D/g75e2LX5ig4tjN/YHf7d63kOq6aspji9U1LVTxAKka716YdMt/vRbNMMBT7dMMn0o4iPaKAD+22SdnzWIdWk9z6RztHntK1J5770s+5EbjqIHDvJc=
  app: ticketee
  on:
    repo: pwdd/ticketee
